### Linear Algebra

#### Question 1 - Partition Matrices 

Given, 

$$ 
X = \begin{bmatrix}
X_1 &  X_2 \\
\end{bmatrix},  \beta = \begin{bmatrix}
\beta_1 \\
\beta_2
\end{bmatrix}$$


$$\hat\beta = (X'X)^{-1}X'y $$


Let's evaluate 

$$
(X'X)^{-1} =\begin{bmatrix}
X_1'X_1 & X_1'X_2 \\
X_2'X_1 & X_2'X_2
\end{bmatrix}^{-1}$$ 

Therefore,

$$
(X'X)^{-1} =\begin{bmatrix}
[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1} & -[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}X_1'X_2(X_2'X_2)^{-1} \\
-[X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}X_2'X_1(X_1'X_1)^{-1} & [X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}
\end{bmatrix}$$


Also, we know that, 



$$
X'y = \begin{bmatrix}
X_1'y \\
X_2'y
\end{bmatrix}$$

Therefore, 


$$
\beta = (X'X)^{-1}X'y =\begin{bmatrix}
[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}X_1'y -[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}X_1'X_2(X_2'X_2)^{-1}X_2'y \\
-[X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}X_2'X_1(X_1'X_1)^{-1}X_1'y + [X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}X_2'y
\end{bmatrix}$$


And now $\beta$ can be written as, 

$$\beta = \begin{bmatrix}
\beta_1 \\
\beta_2
\end{bmatrix} = \begin{bmatrix}
[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}X_1'y -[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}X_1'X_2(X_2'X_2)^{-1}X_2'y \\
-[X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}X_2'X_1(X_1'X_1)^{-1}X_1'y + [X_2'X_2 - X_2'X_1(X_1'X_1)^{-1}X_1'X_2]^{-1}X_2'y
\end{bmatrix}$$


for $\beta_1$, 

$$ \beta_1  = 
[X_1'X_1 - X_1'X_2(X_2'X_2)^{-1}X_2'X_1]^{-1}[X_1'y - X_1'X_2(X_2'X_2)^{-1}X_2'y]$$


From the previous P.S. 1, we remember, 


$$P = X(X'X)^{-1}X'$$

Therefore, 


$$ \beta_1  = 
[X_1'X_1 - X_1'P_2X_1]^{-1}[X_1'y - X_1'P_2y]$$

$$ \beta_1  = 
[X_1'(I_n -P_2)X_1]^{-1}[X_1'(I_n - P_2)y]$$


Since, we know $M = I_n - P$

Therefore

$$ \beta_1  = 
[X_1'M_2X_1]^{-1}[X_1'M_2y]$$

Similarly, 

$$ \beta_2  = 
[X_2'M_1X_2]^{-1}[X_2'M_1y]$$


Moreover, $My = \hat{e}$ therefore

$$\beta = \begin{bmatrix}
\beta_1 \\
\beta_2
\end{bmatrix} = \begin{bmatrix} 
[X_1'M_2X_1]^{-1}[X_1'\hat{e_2}] \\
[X_2'M_1X_2]^{-1}[X_2'\hat{e_1}]
\end{bmatrix} $$


### Programming 

#### Question 2: Newey-West Estimator

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("BWGHT.csv")
df.head()

faminc  cigtax  cigprice  bwght  fatheduc  motheduc  parity  male  white  \
0    13.5    16.5     122.3    109      12.0      12.0       1     1      1   
1     7.5    16.5     122.3    133       6.0      12.0       2     1      0   
2     0.5    16.5     122.3    129       NaN      12.0       2     0      0   
3    15.5    16.5     122.3    126      12.0      12.0       2     1      0   
4    27.5    16.5     122.3    134      14.0      12.0       2     1      1   

   cigs    lbwght  bwghtlbs  packs   lfaminc  
0     0  4.691348    6.8125    0.0  2.602690  
1     0  4.890349    8.3125    0.0  2.014903  
2     0  4.859812    8.0625    0.0 -0.693147  
3     0  4.836282    7.8750    0.0  2.740840  
4     0  4.897840    8.3750    0.0  3.314186

In [2]:
df['(intercept)'] = 1
x = df[['(intercept)','cigs','faminc']]
y = df['bwght']
b = np.linalg.solve(x.T@x,x.T@y)
e = y-x@b
vb = e.var()*np.linalg.inv(x.T@x)
se = np.sqrt(np.diagonal(vb))
tstat = b/se
tstat

array([111.5923058 ,  -5.06396699,   3.18048888])

In [37]:
class linear_model:
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.b = np.linalg.solve(x.T@x,x.T@y)
        e = y-x@self.b
        self.vb = self.vcov_b(e)
        self.se = np.sqrt(np.diagonal(self.vb))
        self.t = self.b/self.se
        
    def vcov_b(self,e):
        x = self.x
        return e.var()*np.linalg.inv(x.T@x)

class white(linear_model):
    
    def vcov_b(self,e):
        x = self.x
        meat = np.diagflat(e.values**2)
        bread = np.linalg.solve(x.T@x,x.T)
        sandwich = bread@meat@bread.T
        return sandwich

In [59]:
linear_model(x,y).t

array([111.5923058 ,  -5.06396699,   3.18048888])

In [58]:
white(x,y).t

array([112.90005924,  -5.2265898 ,   3.24858029])

In [56]:
class newey(linear_model):
    def vcov_b(self, e):
        # Calculate the diagonal matrix with variances of 'e'
        diag = np.diagflat([e.var()]*len(e))
        
        # Calculate the autocovariance matrix
        auto1 = np.array([e[i]*e[i+1] for i in range(0, len(e)-1)])
        
        # Calculate the two off-diagonal matrices
        diag1 = np.diagflat([np.sum(auto1)/(len(e) - 1)]*(len(e)-1), 1)
        diag2 = np.diagflat([np.sum(auto1)/(len(e) - 1)]*(len(e)-1), -1)
        
        # Calculate the 'meat' of the sandwich estimator
        meat = diag2 + diag + diag1
        
        # Calculate the inverse of the X'X matrix (bread)
        bread = np.linalg.inv(x.T @ x)
        
        # Calculate the robust sandwich estimator for the variance-covariance matrix
        sandwich = bread @ x.T @ meat @ x @ bread
        
        return sandwich


In [57]:
newey(x,y).t

array([110.26791072,  -5.05761134,   3.17422313])

In [1]:
import numpy as np
from cvxopt import matrix, solvers

def ridge_regression(X, y, lambda_reg):
    n, p = X.shape
    Q = X.T @ X + lambda_reg * np.identity(p)
    c = -X.T @ y

    # Define the equality constraint A * β = b (optional).
    A = -np.identity(p)
    b = np.zeros(p)

    # Convert matrices and vectors to CVXOPT format.
    Q = matrix(Q)
    c = matrix(c)
    A = matrix(A)
    b = matrix(b)

    # Solve the quadratic programming problem.
    sol = solvers.qp(Q, c, A, b)

    # Extract the solution (model coefficients).
    beta = np.array(sol['x'])

    return beta

# Example usage:
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([1, 2, 3, 4])
lambda_reg = 0.1

beta = ridge_regression(X, y, lambda_reg)
print("Ridge Regression Coefficients:")
print(beta)


TypeError: 'q' must be a 'd' matrix with one column